name: 'Update by stargazed'

on:
  schedule:
    - cron: 30 0 * * *

jobs:
  build:
    name: 'stargazed update'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: |
          npx stargazed \
            --username herberttn \
            --token ${{ github.token }} \
            --repo "promissing" \
            --sort
